import { createHash } from "node:crypto";
import type { ExecutionStatus } from "./execution-memory.js";
export type ExecutionReceiptStatus="pending"|"submitted"|"confirmed"|"failed"|"unknown";
export interface ExecutionIntent{opportunityId:string;actionId:string;chainId?:number;account?:string;payloadFingerprint?:string;}
export interface ExecutionReceipt{idempotencyKey:string;opportunityId:string;actionId:string;status:ExecutionReceiptStatus;createdAt:string;updatedAt:string;chainId?:number;account?:string;txHash?:string;note?:string;}
export interface ReceiptReservation{reserved:boolean;receipt:ExecutionReceipt;reason:"new"|"already-pending"|"already-submitted"|"already-confirmed"|"already-unknown"|"retryable-failure";}
const normalize=(v:string|undefined)=>(v??"").trim().toLowerCase();
export function createIdempotencyKey(i:ExecutionIntent){return createHash("sha256").update([normalize(i.opportunityId),normalize(i.actionId),i.chainId===undefined?"":String(i.chainId),normalize(i.account),normalize(i.payloadFingerprint)].join("|"),"utf8").digest("hex");}
const clone=(r:ExecutionReceipt)=>({...r});
function reservationReason(s:ExecutionReceiptStatus):ReceiptReservation["reason"]{switch(s){case"pending":return"already-pending";case"submitted":return"already-submitted";case"confirmed":return"already-confirmed";case"unknown":return"already-unknown";case"failed":return"retryable-failure";}}
export class ExecutionReceiptStore{private readonly receipts=new Map<string,ExecutionReceipt>();reserve(i:ExecutionIntent,t:string){const k=createIdempotencyKey(i),e=this.receipts.get(k);if(e&&e.status!=="failed")return{reserved:false,receipt:clone(e),reason:reservationReason(e.status)};const r={idempotencyKey:k,opportunityId:i.opportunityId,actionId:i.actionId,status:"pending" as const,createdAt:e?.createdAt??t,updatedAt:t,chainId:i.chainId,account:i.account};this.receipts.set(k,r);return{reserved:true,receipt:clone(r),reason:e?"retryable-failure":"new"};}markSubmitted(k:string,t:string,txHash:string,note?:string){return this.update(k,{status:"submitted",updatedAt:t,txHash,note});}markConfirmed(k:string,t:string,txHash?:string,note?:string){return this.update(k,{status:"confirmed",updatedAt:t,txHash,note});}markFailed(k:string,t:string,note?:string){return this.update(k,{status:"failed",updatedAt:t,note});}markUnknown(k:string,t:string,note?:string){return this.update(k,{status:"unknown",updatedAt:t,note});}get(k:string){const r=this.receipts.get(k);return r?clone(r):undefined;}find(i:ExecutionIntent){return this.get(createIdempotencyKey(i));}list(){return[...this.receipts.values()].map(clone);}reconcile(k:string,s:"confirmed"|"failed"|"unknown",t:string,o:{txHash?:string;note?:string}={}){return this.update(k,{status:s,updatedAt:t,txHash:o.txHash,note:o.note});}protected replaceAll(rs:ExecutionReceipt[]){this.receipts.clear();for(const r of rs)this.receipts.set(r.idempotencyKey,clone(r));}protected update(k:string,patch:Partial<ExecutionReceipt>&Pick<ExecutionReceipt,"status"|"updatedAt">){const c=this.receipts.get(k);if(!c)throw new Error(`Unknown execution receipt: ${k}`);const n={...c,...patch};this.receipts.set(k,n);return clone(n);}}
export function receiptStatusFromExecution(status:ExecutionStatus,txHash?:string):ExecutionReceiptStatus{if(txHash)return"submitted";if(status==="failed"||status==="skipped")return"failed";return"confirmed";}
