import { createHash } from "node:crypto";
import type { ExecutionStatus } from "./execution-memory.js";
export type ExecutionReceiptStatus="pending"|"submitted"|"confirmed"|"failed"|"unknown";
export interface ExecutionIntent{opportunityId:string;actionId:string;chainId?:number;account?:string;payloadFingerprint?:string;}
export interface ExecutionReceipt{idempotencyKey:string;opportunityId:string;actionId:string;status:ExecutionReceiptStatus;createdAt:string;updatedAt:string;chainId?:number;account?:string;txHash?:string;note?:string;}
export interface ReceiptReservation{reserved:boolean;receipt:ExecutionReceipt;reason:"new"|"already-pending"|"already-submitted"|"already-confirmed"|"already-unknown"|"retryable-failure";}
const normalize=(v:string|undefined)=>(v??"").trim().toLowerCase();
export function createIdempotencyKey(intent:ExecutionIntent):string{return createHash("sha256").update([normalize(intent.opportunityId),normalize(intent.actionId),intent.chainId===undefined?"":String(intent.chainId),normalize(intent.account),normalize(intent.payloadFingerprint)].join("|"),"utf8").digest("hex");}
const clone=(r:ExecutionReceipt):ExecutionReceipt=>({...r});
function reservationReason(status:ExecutionReceiptStatus):ReceiptReservation["reason"]{switch(status){case"pending":return"already-pending";case"submitted":return"already-submitted";case"confirmed":return"already-confirmed";case"unknown":return"already-unknown";case"failed":return"retryable-failure";}}
export class ExecutionReceiptStore{private readonly receipts=new Map<string,ExecutionReceipt>();reserve(intent:ExecutionIntent,timestamp:string):ReceiptReservation{const key=createIdempotencyKey(intent),existing=this.receipts.get(key);if(existing&&existing.status!=="failed")return{reserved:false,receipt:clone(existing),reason:reservationReason(existing.status)};const receipt={idempotencyKey:key,opportunityId:intent.opportunityId,actionId:intent.actionId,status:"pending" as const,createdAt:existing?.createdAt??timestamp,updatedAt:timestamp,chainId:intent.chainId,account:intent.account};this.receipts.set(key,receipt);return{reserved:true,receipt:clone(receipt),reason:existing?"retryable-failure":"new"};}
markSubmitted(k:string,t:string,txHash:string,note?:string){return this.update(k,{status:"submitted",updatedAt:t,txHash,note});}markConfirmed(k:string,t:string,txHash?:string,note?:string){return this.update(k,{status:"confirmed",updatedAt:t,txHash,note});}markFailed(k:string,t:string,note?:string){return this.update(k,{status:"failed",updatedAt:t,note});}markUnknown(k:string,t:string,note?:string){return this.update(k,{status:"unknown",updatedAt:t,note});}get(k:string){const r=this.receipts.get(k);return r?clone(r):undefined;}find(i:ExecutionIntent){return this.get(createIdempotencyKey(i));}list(){return[...this.receipts.values()].map(clone);}reconcile(k:string,status:"confirmed"|"failed"|"unknown",t:string,o:{txHash?:string;note?:string}={}){return this.update(k,{status,updatedAt:t,txHash:o.txHash,note:o.note});}
private update(k:string,patch:Partial<ExecutionReceipt>&Pick<ExecutionReceipt,"status"|"updatedAt">){const current=this.receipts.get(k);if(!current)throw new Error(`Unknown execution receipt: ${k}`);const next={...current,...patch};this.receipts.set(k,next);return clone(next);}}
export function receiptStatusFromExecution(status:ExecutionStatus,txHash?:string):ExecutionReceiptStatus{if(status==="failed"||status==="skipped")return"failed";return txHash?"submitted":"confirmed";}
