import type { ProjectOpportunity } from "./types.js";
export interface OpportunitySource{readonly id:string;readonly name:string;discover():ProjectOpportunity[];}
export interface AsyncOpportunitySource{readonly id:string;readonly name:string;discover():Promise<ProjectOpportunity[]>;}
export class StaticOpportunitySource implements OpportunitySource{readonly id:string;readonly name:string;private readonly opportunities:ProjectOpportunity[];constructor(id:string,name:string,opportunities:ProjectOpportunity[]=[]){this.id=id;this.name=name;this.opportunities=opportunities.map(cloneOpportunity);}discover(){return this.opportunities.map(cloneOpportunity);}}
export interface OpportunityHttpResponse{ok:boolean;status:number;json():Promise<unknown>;}export type OpportunityHttpFetcher=(input:string,init?:{method?:string;headers?:Record<string,string>;signal?:AbortSignal})=>Promise<OpportunityHttpResponse>;
export interface HttpOpportunitySourceOptions{id:string;name:string;url:string;timeoutMs?:number;headers?:Record<string,string>;fetcher?:OpportunityHttpFetcher;}
export class HttpOpportunitySource implements AsyncOpportunitySource{readonly id:string;readonly name:string;private readonly url:string;private readonly timeoutMs:number;private readonly headers:Record<string,string>;private readonly fetcher:OpportunityHttpFetcher;constructor(o:HttpOpportunitySourceOptions){if(!o.id.trim())throw new Error("Opportunity source id is required");if(!o.name.trim())throw new Error("Opportunity source name is required");if(!o.url.trim())throw new Error("Opportunity source URL is required");const timeout=o.timeoutMs??10000;if(!Number.isFinite(timeout)||timeout<=0)throw new Error("Opportunity source timeout must be a positive number");this.id=o.id;this.name=o.name;this.url=o.url;this.timeoutMs=timeout;this.headers={accept:"application/json",...o.headers};this.fetcher=o.fetcher??((input,init)=>fetch(input,init));}async discover(){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),this.timeoutMs);try{const response=await this.fetcher(this.url,{method:"GET",headers:this.headers,signal:controller.signal});if(!response.ok)throw new Error(`Opportunity source ${this.id} returned HTTP ${response.status}`);const payload=await response.json();return extractOpportunityRecords(payload).map((record,index)=>cloneOpportunity(parseOpportunity(record,this.id,index)));}catch(error){if(controller.signal.aborted)throw new Error(`Opportunity source ${this.id} timed out after ${this.timeoutMs}ms`);throw error;}finally{clearTimeout(timer);}}}
export function mergeOpportunitySources(sources:OpportunitySource[]){const byId=new Map<string,ProjectOpportunity>();for(const source of sources)for(const opportunity of source.discover())mergeOpportunity(byId,opportunity);return[...byId.values()];}
export async function mergeAsyncOpportunitySources(sources:Array<OpportunitySource|AsyncOpportunitySource>){const byId=new Map<string,ProjectOpportunity>();const batches=await Promise.all(sources.map(s=>s.discover()));for(const opportunities of batches)for(const opportunity of opportunities)mergeOpportunity(byId,opportunity);return[...byId.values()];}
function mergeOpportunity(byId:Map<string,ProjectOpportunity>,o:ProjectOpportunity){const existing=byId.get(o.id);if(!existing){byId.set(o.id,cloneOpportunity(o));return;}byId.set(o.id,{...existing,priority:Math.max(existing.priority,o.priority),signals:{...existing.signals,...o.signals},sources:[...new Set([...existing.sources,...o.sources])],actions:[...new Set([...existing.actions,...o.actions])],notes:o.notes??existing.notes});}
function cloneOpportunity(o:ProjectOpportunity):ProjectOpportunity{return{...o,signals:{...o.signals},sources:[...o.sources],actions:[...o.actions]};}
function extractOpportunityRecords(payload:unknown):unknown[]{if(Array.isArray(payload))return payload;if(isRecord(payload)&&Array.isArray(payload.opportunities))return payload.opportunities;throw new Error("Opportunity source payload must be an array or { opportunities: [] }");}
function parseOpportunity(value:unknown,sourceId:string,index:number):ProjectOpportunity{if(!isRecord(value))throw new Error(`Opportunity source ${sourceId} record ${index} is not an object`);const id=requiredString(value.id,`record ${index}.id`),name=requiredString(value.name,`record ${index}.name`),vm=value.vm,stage=value.stage,priority=value.priority;if(vm!=="EVM"&&vm!=="SUI"&&vm!=="CUSTOM")throw new Error(`Opportunity source ${sourceId} record ${index}.vm is invalid`);const stages=new Set(["research","testnet","mainnet","builder-program","incentivized"]);if(typeof stage!=="string"||!stages.has(stage))throw new Error(`Opportunity source ${sourceId} record ${index}.stage is invalid`);if(typeof priority!=="number"||!Number.isFinite(priority))throw new Error(`Opportunity source ${sourceId} record ${index}.priority is invalid`);return{id,name,chainId:optionalNumber(value.chainId,`record ${index}.chainId`),vm,stage:stage as ProjectOpportunity["stage"],priority,signals:parseSignals(value.signals,sourceId,index),sources:[...new Set([...stringArray(value.sources,`record ${index}.sources`),sourceId])],actions:stringArray(value.actions,`record ${index}.actions`),notes:value.notes===undefined?undefined:requiredString(value.notes,`record ${index}.notes`)};}
function parseSignals(value:unknown,sourceId:string,index:number):ProjectOpportunity["signals"]{if(value===undefined)return{};if(!isRecord(value))throw new Error(`Opportunity source ${sourceId} record ${index}.signals is invalid`);const allowed=["fundingUsd","fundingEvidence","developerProgram","testnetActivity","mainnetReadiness","onchainVerifiability","ecosystemActivity","rewardSignals","userFit","timing"] as const;const result:ProjectOpportunity["signals"]={};for(const key of allowed){if(value[key]===undefined)continue;if(typeof value[key]!=="number"||!Number.isFinite(value[key]))throw new Error(`Opportunity source ${sourceId} record ${index}.signals.${key} is invalid`);result[key]=value[key];}return result;}
function stringArray(value:unknown,path:string){if(!Array.isArray(value)||!value.every(i=>typeof i==="string"&&i.trim()))throw new Error(`Opportunity source ${path} must be a non-empty string array`);return value.map(i=>i.trim());}
function optionalNumber(value:unknown,path:string){if(value===undefined)return undefined;if(typeof value!=="number"||!Number.isFinite(value))throw new Error(`Opportunity source ${path} is invalid`);return value;}
function requiredString(value:unknown,path:string){if(typeof value!=="string"||!value.trim())throw new Error(`Opportunity source ${path} is required`);return value.trim();}
function isRecord(value:unknown):value is Record<string,any>{return typeof value==="object"&&value!==null&&!Array.isArray(value);}
