export type OpportunityLifecycle="active"|"stale"|"retired";
export type RewardEvidenceStatus="confirmed"|"unconfirmed"|"contradicted";
export type MonitorConfidence="low"|"medium"|"high";
export interface OpportunityObservation{opportunityId:string;name:string;score:number;observedAt:string;lifecycle:OpportunityLifecycle;confidence:MonitorConfidence;rewardEvidence:RewardEvidenceStatus;sourceCount:number;recommendedActionIds:string[];chainKeys:string[];notes?:string[];}
export interface OpportunitySnapshot extends OpportunityObservation{firstSeenAt:string;lastSeenAt:string;observationCount:number;scoreDelta:number;}
export interface OpportunityMonitorConfig{staleAfterMs:number;minActionScore:number;maxObservationsPerOpportunity:number;}
export interface MonitorUpdate{snapshot:OpportunitySnapshot;isNew:boolean;scoreChanged:boolean;lifecycleChanged:boolean;becameActionable:boolean;}
const DEFAULT_CONFIG={staleAfterMs:7*24*60*60*1000,minActionScore:60,maxObservationsPerOpportunity:32};
const confidenceRank:Record<MonitorConfidence,number>={low:1,medium:2,high:3};
function clampScore(s:number){return Math.max(0,Math.min(100,s));}
function highestConfidence(a:MonitorConfidence,b:MonitorConfidence):MonitorConfidence{return confidenceRank[b]>confidenceRank[a]?b:a;}
function normalizeTimestamp(v:string){const t=Date.parse(v);if(Number.isNaN(t))throw new Error(`Invalid observation timestamp: ${v}`);return t;}
function cloneObservation(o:OpportunityObservation):OpportunityObservation{return{...o,recommendedActionIds:[...o.recommendedActionIds],chainKeys:[...o.chainKeys],notes:o.notes?[...o.notes]:undefined};}
export class OpportunityMonitor{private readonly config:OpportunityMonitorConfig;private readonly history=new Map<string,OpportunityObservation[]>();constructor(config:Partial<OpportunityMonitorConfig>={}){this.config={...DEFAULT_CONFIG,...config};if(this.config.staleAfterMs<=0)throw new Error("staleAfterMs must be positive");if(this.config.maxObservationsPerOpportunity<=0)throw new Error("maxObservationsPerOpportunity must be positive");}
observe(observation:OpportunityObservation):MonitorUpdate{const current=this.history.get(observation.opportunityId)??[];const previous=current[current.length-1];const normalized=cloneObservation({...observation,score:clampScore(observation.score)});this.history.set(observation.opportunityId,[...current,normalized].slice(-this.config.maxObservationsPerOpportunity));const snapshot=this.snapshot(observation.opportunityId);const scoreChanged=previous?previous.score!==normalized.score:false;const lifecycleChanged=previous?previous.lifecycle!==normalized.lifecycle:false;const wasActionable=previous?previous.score>=this.config.minActionScore:false;return{snapshot,isNew:!previous,scoreChanged,lifecycleChanged,becameActionable:normalized.score>=this.config.minActionScore&&!wasActionable};}
snapshot(id:string):OpportunitySnapshot{const observations=this.history.get(id);if(!observations?.length)throw new Error(`Unknown opportunity: ${id}`);const first=observations[0],latest=observations[observations.length-1];return{...cloneObservation(latest),firstSeenAt:first.observedAt,lastSeenAt:latest.observedAt,observationCount:observations.length,scoreDelta:latest.score-first.score};}
list(options:{lifecycle?:OpportunityLifecycle;minScore?:number}={}):OpportunitySnapshot[]{return[...this.history.keys()].map(id=>this.snapshot(id)).filter(i=>!options.lifecycle||i.lifecycle===options.lifecycle).filter(i=>options.minScore===undefined||i.score>=options.minScore).sort((a,b)=>b.score-a.score||b.lastSeenAt.localeCompare(a.lastSeenAt));}
actionable(){return this.list({lifecycle:"active",minScore:this.config.minActionScore});}
refreshStale(now:string):OpportunitySnapshot[]{const nowMs=normalizeTimestamp(now);const changed:OpportunitySnapshot[]=[];for(const[id,observations]of this.history.entries()){const latest=observations[observations.length-1];if(latest.lifecycle!=="active")continue;if(nowMs-normalizeTimestamp(latest.observedAt)<=this.config.staleAfterMs)continue;const update={...latest,observedAt:now,lifecycle:"stale" as const,notes:[...(latest.notes??[]),"Marked stale because no fresh observation arrived within the configured window."]};this.history.set(id,[...observations,update].slice(-this.config.maxObservationsPerOpportunity));changed.push(this.snapshot(id));}return changed;}
retire(id:string,observedAt:string,note?:string){const latest=this.snapshot(id);const update={...latest,observedAt,lifecycle:"retired" as const,notes:[...(latest.notes??[]),...(note?[note]:[])]};this.history.set(id,[...(this.history.get(id)??[]),update].slice(-this.config.maxObservationsPerOpportunity));return this.snapshot(id);}
historyFor(id:string){return(this.history.get(id)??[]).map(cloneObservation);}size(){return this.history.size;}}
export function mergeOpportunityConfidence(current:MonitorConfidence,incoming:MonitorConfidence):MonitorConfidence{return highestConfidence(current,incoming);}
